### ISSUE TITLE
Set delay or debounce

### ISSUE THREAD

**Issue by arnaudlip** [maxeckel/livewire-editorjs#10]
Hello,

Thank you so much for this package, works like a charm.

I just have a concern about the frequency of upload data. Is there a way to apply delay ou debounce ?

Thanks.

**Comment by pirmax** [comment]
I want this feature too...

**Comment by maxeckel** [comment]
Hey Folks,

as you might have seen I've already created #9 as I already thought about this.

Sadly I don't have the time right now to take care of this.
