### ISSUE TITLE
In production, auto save on editor block the focus

### ISSUE THREAD

**Issue by pirmax** [maxeckel/livewire-editorjs#11]
Hi,

In production, the auto save feature block the focus on editor... I type text and the focus is blocked after 1 to 2 seconds.

    protected $listeners = [
        'editorjs-save:editor' => 'autoSave',
    ];

    public function autoSave(array $json)
    {
        $this->content = $json;
    }

The Livewire component:

    <livewire:admin.partials.custom-editor-component
                        :key="time()"
                        editor-id="editor"
                        :value="$content"
                        upload-disk="s3"
                        download-disk="s3"
                        class="min-h-screen"
                        :read-only="false"
                        :post="$post"
                        placeholder="Saisissez votre nouvelle histoire..."
                />

Thanks for help!

**Comment by maxeckel** [comment]
Hey @pirmax 

this probably results from your autosave triggering a rerender of the component.

You should be able to avoid this by using wire:ignore.
