### ISSUE TITLE
Shows two editor when Alpine version 3 is used

### ISSUE THREAD

**Issue by mithicher** [maxeckel/livewire-editorjs#21]
Can you please make it compatible with alpine.js version 3...

![Screenshot 2021-11-18 at 2 22 38 PM](https://user-images.githubusercontent.com/5371513/142382886-11a5f746-e9fe-456b-ae1b-eefef2a214c0.png)

**Comment by maxeckel** [comment]
Hey @mithicher,

thanks for reporting this issue. I think it is related to v3 automatically calling "init" methods.

I'll release a fix for this later today!

Kind regards,

Max

**Comment by mithicher** [comment]
Thanks @maxeckel
